### ISSUE TITLE
Status Page Not Updating

### ISSUE THREAD

**Issue by BeckyBaltes** [ioos/ioosngdac#126]
@benjwadams @bobfrat @kerfoot, Please move to different repo if more appropriate.  The status page, https://gliders.ioos.us/status/ has a most recent update of July 27 though the map clearly shows gliders reporting as of yesterday.  Please investigate why it isn't updating.

**Comment by kerfoot** [comment]
@benjwadams any update on this?  The status page is the primary means by which I check dataset status and it would be great if it worked. I believe that @lukecampbell had this running on a cronjob and it had been updating regularly prior to July 27.  So, something must have happened since then to prevent the updates.

**Comment by benjwadams** [comment]
Hey John, I looked at this more today, and the logs indicate that the status is having some issues retrieving the trajectories:

```
2017-08-07 21:58:40 [25506] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/glider/.virtualenvs/gliderdac/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 103, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/glider/.virtualenvs/gliderdac/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/glider/glider-dac-status/status/reverse_proxy.py", line 37, in __call__
    return self.app(environ, start_response)
  File "/home/glider/.virtualenvs/gliderdac/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/glider/.virtualenvs/gliderdac/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/glider/.virtualenvs/gliderdac/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/glider/.virtualenvs/gliderdac/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/glider/.virtualenvs/gliderdac/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/glider/.virtualenvs/gliderdac/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/glider/.virtualenvs/gliderdac/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/glider/glider-dac-status/status/controller.py", line 46, in track
    geo_data = get_trajectory(erddap_url)
  File "/home/glider/glider-dac-status/status/tasks.py", line 53, in get_trajectory
    raise IOError("Failed to get trajectories")
IOError: Failed to get trajectories
```

**Comment by benjwadams** [comment]
```
--------------------------------------------------------------------------------                                                                                                                                                              
INFO in app [/home/glider/glider-dac-status/app.py:49]:                                                                                                                                                                                       
Application Process Started                                                                                                                                                                                                                   
--------------------------------------------------------------------------------                                                                                                                                                              
0x7fb5e59605d0                                                                                                                                                                                                                                
Traceback (most recent call last):                                                                                                                                                                                                            
  File "manage.py", line 39, in <module>                                                                                                                                                                                                      
    manager.run()                                                                                                                                                                                                                             
  File "/home/glider/.virtualenvs/gliderdac/lib/python2.7/site-packages/flask_script/__init__.py", line 412, in run                                                                                                                           
    result = self.handle(sys.argv[0], sys.argv[1:])                                                                                                                                                                                           
  File "/home/glider/.virtualenvs/gliderdac/lib/python2.7/site-packages/flask_script/__init__.py", line 383, in handle                                                                                                                        
    res = handle(*args, **config)                                                                                                                                                                                                             
  File "/home/glider/.virtualenvs/gliderdac/lib/python2.7/site-packages/flask_script/commands.py", line 216, in __call__                                                                                                                      
    return self.run(*args, **kwargs)                                                                                                                                                                                                          
  File "manage.py", line 12, in get_status                                                                                                                                                                                                    
    result.wait()                                                                                                                                                                                                                             
  File "/home/glider/.virtualenvs/gliderdac/lib/python2.7/site-packages/celery/result.py", line 175, in get                                                                                                                                   
    raise meta['result']                                                                                                                                                                                                                      
AttributeError: 'NoneType' object has no attribute 'groups'
```

**Comment by benjwadams** [comment]
@jkerfoot, Applied a hotfix for now.  If time_coverage_start or time_coverage_end aren't defined in the dataset, an unhandled exception was thrown, causing the status update to fail.
In this case, the first particular dataset to cause this to fail was
https://data.ioos.us/gliders/erddap/tabledap/Nemesis-20170512T0000.das

I set up a pull request at, https://github.com/ioos/glider-dac-status/pull/20 but haven't merged into master, as I don't know if you want to consider it an error that time coverage is not present.  In any case, production is checked out on this branch for the time being so as to allow generation of the status page.

**Comment by benjwadams** [comment]
Status page is updating again.  Closing.
